### ISSUE TITLE
Error reading codeplug from TYT MD UV380

### ISSUE THREAD

**Issue by iamtherealtomlewis** [hmatuschek/qdmr#101]
I'm using 0.5.3 as it seems to be the latest that will support Catalina.  Does anyone have an idea about this when trying to download the radio?
![Screen Shot 2021-04-20 at 7 54 09 PM](https://user-images.githubusercontent.com/62721735/115477851-db763400-a212-11eb-8fa2-35426ee3d955.png)

**Comment by hmatuschek** [comment]
This is a bug and is hopefully fixed just today. The fix is part of the 0.7.0 release. However, I doubt that the binary release will run under Catalina (for some unknown reason). So you may need to compile qdmr from sources or put some friendly pressure on macports or homebrew to include qdmr into their distributions.
