### ISSUE TITLE
Callsign upload: extra characters appended to callsigns

### ISSUE THREAD

**Issue by lee-barford** [hmatuschek/qdmr#103]
Severity: minor
Radio model: AT878UV
Sequence of events:
1. Press button labelled Upload Callsign DB to Radio
2. Radio behaves normally during upload
3. All callsigns displayed by radio have extra characters that appear to come from the station location:

Examples:
- GM4KHE is Scotland shows as "GM4KHESc". 
- K2FUN in Nevada, US shows as "K2FUNNev"

If this is the intended behavior, then please note that in the documentation.

**Comment by hmatuschek** [comment]
Thanks for the report. No it is certainly not intentional. The callsign DB for the D868 and D878 is encoded somewhat weird. Each entry is of variable size and consists of a small header followed by up to 6 0-termined strings. I just forgot to terminate the callsign string. Thus the callsign and state where merged into one string. The callsign, however, is limited to 8 chars. Consequently "GM4KHE" + "Scotland" = "GM4KHESc".

**Comment by hmatuschek** [comment]
Fixed in repo, will be fixed in the next release 0.7.1.
