### ISSUE TITLE
Update OpenGD77 support

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#394]
This is a larger change. With the support of other radios, the OpenGD77 firmare changes the codeplug and callsign DB format. To this end, a detection of the firmware variant is needed and some device specific implementation of the codeplug/callsign DB. Hence the following sub-steps are needed. (Unifies issues #393, #300, #297, #239, #223)

- [x] Implement variant detection (update communication protocol).
- [x] Infer and implement common OpenGD77Base/OpenUV380
  - [x] Codeplug
  - [x] Call-sign DB
- [x] ~~Update OpenDM1801A~~ Identical to OpenGD77
  - [x] ~~Codeplug~~
  - [x] ~~Call-sign DB~~
- [x] Update OpenGD77
  - [x] Codeplug
  - [x] Call-sign DB
- [x] ~~Update OpenRD5R~~ Identical to OpenGD77
  - [x] ~~Codeplug~~
  - [x] ~~Call-sign DB~~
- [x] ~~Implement OpenMD1701~~ Identical to OpenUV380
  - [x] ~~Codeplug~~
  - [x] ~~Call-sign DB~~
- [x] Implement OpenUV380
  - [x] Codeplug
  - [x] Call-sign DB
- [x] Test, test, test

**Comment by luzemario** [comment]
Does qDMR support STM32 radios?

**Comment by luzemario** [comment]
Yeah, I own a DM-1701 running OpenGD77. And yes, some fields are garbled when reading the radio. You is correct.

**Comment by hmatuschek** [comment]
Does anyone know, where I can get the source code of the latest OpenGD77 CPS and firmware? It is super weird to treat this *open source* firmware like any other shitty commercial one, needing to reverse engineer everything from scratch.

**Comment by luzemario** [comment]
Maybe this can be useful:

[https://www.opengd77.com/viewtopic.php?f=19&t=2742](url)

The interface code has changed a bit since then, but not too often.

**Comment by hmatuschek** [comment]
Thanks, that helps a lot.

**Comment by Pleune** [comment]
I have a OpenGD77-ified MDUV380 that I would really like to use qdmr to program, since I think their CPS is really not the best... It seems like this project is close already. I have tested your recent work that it does correctly identify my radio and mark it as unsupported. If I use the existing OpenGD77 class anyways, it reads contacts and zones fine aside from some extra garbage entries, but zones / TGs are not read. And writing makes no change to the radio after it completes, even though the radio shows all the right screens.

Is this something you expect to be working on in the coming months?  If not, I may try to make the changes to support at least the new format/protocol, at least for my radio. But I do not want to duplicate any effort here.

**Comment by luzemario** [comment]
OpenGD77 format is almost the same across different models, with slightly differences for MD9600 and other mobiles. Once it works with one of them, maybe will work for all with Opengd77 firmware installed.

**Comment by hmatuschek** [comment]
Just to keep you updated. I'll release 0.12.1 soon with an updated OpenGD77 and OpenMDUV380 support. Please also consider to participate in the discussion at issue #497 on how the orbital elements are updated.

**Comment by Pleune** [comment]
Sweet, I will take a look at this soon
