### ISSUE TITLE
download from radio gets stuck after error "Cannot link group list" (OpenGD77 DM-1701)

### ISSUE THREAD

**Issue by ec1oud** [hmatuschek/qdmr#489]
I wrote the first codeplug on Windows after installing firmware.  Tried to download it with qdmr, and I get this error:

![image](https://github.com/user-attachments/assets/1ff7d327-ae7a-4535-a33f-b6b5e93750cf)

After dismissing that, the progress bar at the bottom of the main window stays at 99%.  But maybe it could just skip the things that don't make sense to it, and keep the rest?  But I see #394 , must be the reason I suppose.

**Comment by DennisD2** [comment]
Same issue here, even with same "member index 8292".

**Comment by hmatuschek** [comment]
Yes and no. The issue is (was) that the OpenGD77 codeplug was derived from the Radioddity one, because they are quiet similar. Radioddity codeplugs (like every other codeplug), however, only allow group calls in group lists (they are called group lists for exactly that reason). Wit the next release, OpenGD77 are independent from all other codeplugs and therefore I can fix this issue. 

However, to be sure to fix it, can you read the binary codeplug from the device and attach it here? This helps in reproducing the issue. Simply use the command line tool 
```
dmrconf read codeplug_opengd77_grouplist_issue.dfu
```

**Comment by ec1oud** [comment]
[codeplug_opengd77_grouplist_issue.dfu.gz](https://github.com/user-attachments/files/18272980/codeplug_opengd77_grouplist_issue.dfu.gz)
Sorry for late response: this is with dmrconf 0.12.0.  Now I will try to upgrade.

**Comment by ec1oud** [comment]
And after the upgrade (qdmr-git from AUR) yes I can read everything from the radio, AFAICT.  Thanks!
